// "packages": {
//     "": {
//       "name": "jobly-frontend",
//       "version": "0.1.0",
//       "dependencies": {
//         "@emotion/react": "^11.7.1",
//         "@emotion/styled": "^11.6.0",
//         "@material-ui/core": "^4.12.3",
//         "@mui/icons-material": "^5.3.1",
//         "@testing-library/jest-dom": "^5.16.1",
//         "@testing-library/react": "^12.1.2",
//         "@testing-library/user-event": "^13.5.0",
//         "axios": "^0.25.0",
//         "formik": "^2.2.9",
//         "jsonwebtoken": "^8.5.1",
//         "react": "^17.0.2",
//         "react-dom": "^17.0.2",
//         "react-router-dom": "^6.2.1",
//         "react-scripts": "5.0.0",
//         "web-vitals": "^2.1.4"
//       }

// "dependencies": {
//     "@emotion/react": "^11.7.1",
//     "@emotion/styled": "^11.6.0",
//     "@material-ui/core": "^4.12.3",
//     "@mui/icons-material": "^5.3.1",
//     "@testing-library/jest-dom": "^5.16.1",
//     "@testing-library/react": "^12.1.2",
//     "@testing-library/user-event": "^13.5.0",
//     "axios": "^0.25.0",
//     "formik": "^2.2.9",
//     "jsonwebtoken": "^8.5.1",
//     "react": "^17.0.2",
//     "react-dom": "^17.0.2",
//     "react-router-dom": "^6.2.1",
//     "react-scripts": "5.0.0",
//     "web-vitals": "^2.1.4"